### ISSUE TITLE
suggested edits to gross_chechs/README

### ISSUE THREAD

**Issue by LydiaStefanova-NOAA** [rgrumbine/ice_scoring#2]
Bob, 

I'm trying the "submit issue" feature for the first time, so apologies if that's not the appropriate thing to use for this. 

The README in gross_checks (https://github.com/rgrumbine/ice_scoring/blob/develop/gross_checks/README) has obsolete instructions for the path that needs to be added on Hera

It currently says 

> add /home/Robert.Grumbine/clim_data/anaconda3/bin to your PATH

I suggest specifying that one should prepend the path (since adding it to the end doesn't work), so I would change that to 

> prepend  /scratch2/NCEPDEV/climate/Robert.Grumbine/python3_anaconda3/bin to your PATH

FYI, I noticed that when I do that, I can no longer use the "clear" command on my screen. To fix that, in my .cshrc, after setting the path as above, I had to add the line 

> setenv TERMINFO /usr/share/terminfo

**Comment by rgrumbine** [comment]
Lydia,

works for me. I've updated the readme, and added delta_ice.py -- which now lets one compare two model runs, as we are for CCPP vs. IPD.
